/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import jugadores.Jugador;

/**
 *
 * @author Estuardo Ramos
 */
public class PruebaTabla extends javax.swing.JFrame {

    /**
     * Creates new form PruebaTabla
     */
    public PruebaTabla() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Inicio partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButton1)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jButton1)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Jugador jugador1 = new Jugador(10, "CArlito", "marque");
        Jugador jugador2 = new Jugador(12, "mmmmm", "lop");
        Tablero tablero = new Tablero(8, 6, jugador1, jugador2);
        //tablero(6,8)
        tablero.retrocede(0, 1, 4);
        tablero.tiradados(0, 3);
        tablero.subida(0, 4, 2, 6);
        tablero.retrocede(0, 6, 6);
        tablero.avanza(0, 7, 1);
        tablero.avanza(1, 0, 4);
        tablero.avanza(1, 1, 7);
        tablero.pierdeturno(1, 3);
        tablero.retrocede(1, 4, 9);
        tablero.pierdeturno(1, 5);
        tablero.retrocede(1, 6, 3);
        tablero.pierdeturno(2, 0);
        tablero.tiradados(2, 1);
        tablero.pierdeturno(2, 2);
        tablero.bajada(2, 4, 0, 4);
        tablero.tiradados(2, 6);
        tablero.avanza(2, 7, 4);
        tablero.tiradados(3, 0);
        tablero.avanza(3, 2, 6);
        tablero.tiradados(3, 3);
        tablero.avanza(3, 5, 2);
        tablero.retrocede(3, 6, 4);
        tablero.subida(4, 0, 5, 5);
        tablero.retrocede(4, 1, 4);
        tablero.pierdeturno(4, 3);
        tablero.avanza(4, 4, 5);
        tablero.tiradados(4, 5);
        tablero.bajada(4, 6, 2, 4);
        tablero.pierdeturno(5, 0);
        tablero.tiradados(5, 1);
        tablero.retrocede(5, 3, 3);
        tablero.subida(5, 5, 5, 7);
        tablero.retrocede(5, 6, 3);
        //tablero.subida(3, 4, 4, 3);
        tablero.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
